"""company id is added in invoices

Revision ID: 0cc4f23a839d
Revises: 9a063307463d
Create Date: 2025-12-18 12:34:04.564134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc4f23a839d'
down_revision: Union[str, Sequence[str], None] = '9a063307463d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('client_company', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'companies', ['client_company'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'client_company')
    # ### end Alembic commands ###
