"""Add offer dates to Candidate

Revision ID: 1e09678a3b9c
Revises: 08dfa4f6f340
Create Date: 2025-12-09 15:20:14.146577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e09678a3b9c'
down_revision: Union[str, Sequence[str], None] = '08dfa4f6f340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('offer_made_date', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('offer_acceptence_date', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('offer_rejected_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'offer_rejected_date')
    op.drop_column('candidates', 'offer_acceptence_date')
    op.drop_column('candidates', 'offer_made_date')
    # ### end Alembic commands ###
