"""interviewers list added

Revision ID: 59096dafb654
Revises: a1fd91c84100
Create Date: 2025-12-18 08:26:11.941141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '59096dafb654'
down_revision: Union[str, Sequence[str], None] = 'a1fd91c84100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_interviewers',
    sa.Column('interview_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interview_id', 'user_id')
    )
    op.drop_column('interviews', 'interviewers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('interviewers', mysql.TEXT(), nullable=True))
    op.drop_table('interview_interviewers')
    # ### end Alembic commands ###
