"""initial tables

Revision ID: 78f29dafbe4b
Revises: 
Create Date: 2025-11-19 23:14:53.839509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '78f29dafbe4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_constraint(op.f('candidate_activity_logs_ibfk_1'), 'candidate_activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'candidate_activity_logs', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.alter_column('candidates', 'reject_reason',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('invoice_items', 'description',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('invoices', 'to_address',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('invoices', 'place_of_supply',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('invoices', 'payment_terms',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('invoices', 'service_description',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('invoices', 'item_description',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('invoices', 'pdf_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('requisitions', 'req_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('requisitions', 'approval_status',
               existing_type=mysql.VARCHAR(length=100),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('requisition_id'), table_name='requisitions')
    op.create_index(op.f('ix_requisitions_req_id'), 'requisitions', ['req_id'], unique=True)
    op.drop_column('requisitions', 'filled_position')
    op.alter_column('users', 'company_desc',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_desc',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.add_column('requisitions', sa.Column('filled_position', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_requisitions_req_id'), table_name='requisitions')
    op.create_index(op.f('requisition_id'), 'requisitions', ['req_id'], unique=True)
    op.alter_column('requisitions', 'approval_status',
               existing_type=mysql.VARCHAR(length=100),
               server_default=sa.text("'pending'"),
               existing_nullable=True)
    op.alter_column('requisitions', 'req_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('invoices', 'pdf_url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('invoices', 'item_description',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('invoices', 'service_description',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('invoices', 'payment_terms',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('invoices', 'place_of_supply',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('invoices', 'to_address',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('invoice_items', 'description',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('candidates', 'reject_reason',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'candidate_activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('candidate_activity_logs_ibfk_1'), 'candidate_activity_logs', 'candidates', ['candidate_id'], ['id'])
    op.create_table('password_reset_tokens',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_tokens_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_table('positions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('requisition_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('skills', mysql.TEXT(), nullable=True),
    sa.Column('position_desc', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], name=op.f('positions_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    # ### end Alembic commands ###
