"""initial schema

Revision ID: 89c03aad1588
Revises: 
Create Date: 2025-11-30 13:02:41.819635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '89c03aad1588'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_address', sa.Text(), nullable=True),
    sa.Column('envelope_id', sa.String(length=200), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('gstin', sa.String(length=100), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('place_of_supply', sa.String(length=255), nullable=True),
    sa.Column('service_description', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_table('salary_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('grade', sa.String(length=64), nullable=False),
    sa.Column('min_amount', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country', 'grade', name='uq_country_grade')
    )
    op.create_index(op.f('ix_salary_bands_country'), 'salary_bands', ['country'], unique=False)
    op.create_index(op.f('ix_salary_bands_grade'), 'salary_bands', ['grade'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('company_size', sa.String(length=100), nullable=True),
    sa.Column('company_desc', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('uom', sa.String(length=100), nullable=True),
    sa.Column('taxable_value', sa.Float(), nullable=True),
    sa.Column('gst', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_table('requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', name='employmenttype'), nullable=False),
    sa.Column('work_mode', sa.Enum('ONSITE', 'REMOTE', 'HYBRID', name='workmode'), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'ON_HOLD', 'CANCELLED', name='status'), nullable=False),
    sa.Column('approval_status', sa.String(length=100), nullable=True),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('max_salary', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('positions_count', sa.Integer(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('target_startdate', sa.Date(), nullable=True),
    sa.Column('hiring_manager', sa.String(length=100), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('recruiter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisitions_id'), 'requisitions', ['id'], unique=False)
    op.create_index(op.f('ix_requisitions_req_id'), 'requisitions', ['req_id'], unique=True)
    op.create_table('candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('skills', sqlite.JSON(), nullable=True),
    sa.Column('applied_date', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resume_url', sa.String(length=1000), nullable=True),
    sa.Column('recruiter', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('reject_reason', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('requisition_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('current_ctc', sa.String(length=50), nullable=True),
    sa.Column('expected_ctc', sa.String(length=50), nullable=True),
    sa.Column('notice_period', sa.String(length=50), nullable=True),
    sa.Column('current_company', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('requisition_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisition_activity_logs_id'), 'requisition_activity_logs', ['id'], unique=False)
    op.create_table('requisition_recruiter',
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('requisition_id', 'user_id')
    )
    op.create_table('candidate_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_activity_logs_id'), 'candidate_activity_logs', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('candidate_id', sa.String(length=100), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('interview_type', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=100), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('meeting_link', sa.String(length=100), nullable=True),
    sa.Column('interviewers', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.String(length=64), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('grade', sa.String(length=64), nullable=False),
    sa.Column('base', sa.Float(), nullable=False),
    sa.Column('allowances', sqlite.JSON(), nullable=True),
    sa.Column('benefits', sqlite.JSON(), nullable=True),
    sa.Column('variable_pay', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'LETTER_GENERATED', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='offerstatus'), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('letter_blob_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['requisitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['letter_blob_id'], ['blobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_grade'), 'offers', ['grade'], unique=False)
    op.create_index(op.f('ix_offers_offer_id'), 'offers', ['offer_id'], unique=True)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_table('approval_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstate'), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_records_offer_id'), 'approval_records', ['offer_id'], unique=False)
    op.create_index(op.f('ix_approval_records_state'), 'approval_records', ['state'], unique=False)
    op.create_table('scorecards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=100), nullable=True),
    sa.Column('interview_id', sa.String(length=100), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('behavioral_score', sa.Float(), nullable=True),
    sa.Column('cultural_score', sa.Float(), nullable=True),
    sa.Column('overall_recommendation', sa.String(length=50), nullable=True),
    sa.Column('technical_comments', sa.Text(), nullable=True),
    sa.Column('behavioral_comments', sa.Text(), nullable=True),
    sa.Column('cultural_comments', sa.Text(), nullable=True),
    sa.Column('overall_comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scorecards_id'), 'scorecards', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scorecards_id'), table_name='scorecards')
    op.drop_table('scorecards')
    op.drop_index(op.f('ix_approval_records_state'), table_name='approval_records')
    op.drop_index(op.f('ix_approval_records_offer_id'), table_name='approval_records')
    op.drop_table('approval_records')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_offer_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_grade'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_table('files')
    op.drop_index(op.f('ix_candidate_activity_logs_id'), table_name='candidate_activity_logs')
    op.drop_table('candidate_activity_logs')
    op.drop_table('requisition_recruiter')
    op.drop_index(op.f('ix_requisition_activity_logs_id'), table_name='requisition_activity_logs')
    op.drop_table('requisition_activity_logs')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_requisitions_req_id'), table_name='requisitions')
    op.drop_index(op.f('ix_requisitions_id'), table_name='requisitions')
    op.drop_table('requisitions')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_salary_bands_grade'), table_name='salary_bands')
    op.drop_index(op.f('ix_salary_bands_country'), table_name='salary_bands')
    op.drop_table('salary_bands')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_table('blobs')
    # ### end Alembic commands ###
