"""interviewers created date added

Revision ID: 9a063307463d
Revises: 59096dafb654
Create Date: 2025-12-18 08:47:15.495679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a063307463d'
down_revision: Union[str, Sequence[str], None] = '59096dafb654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('scheduled_at', sa.DateTime(), nullable=False))
    op.add_column('interviews', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.drop_column('interviews', 'datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('datetime', mysql.DATETIME(), nullable=False))
    op.drop_column('interviews', 'created_date')
    op.drop_column('interviews', 'scheduled_at')
    # ### end Alembic commands ###
