"""updating requisiton with created field

Revision ID: a1fd91c84100
Revises: 98b0977df34f
Create Date: 2025-12-10 23:18:45.760978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1fd91c84100'
down_revision: Union[str, Sequence[str], None] = '98b0977df34f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisitions', sa.Column('hiring_manager_id', sa.Integer(), nullable=True))
    op.add_column('requisitions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requisitions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'requisitions', 'users', ['hiring_manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requisitions', type_='foreignkey')
    op.drop_constraint(None, 'requisitions', type_='foreignkey')
    op.drop_column('requisitions', 'created_by')
    op.drop_column('requisitions', 'hiring_manager_id')
    # ### end Alembic commands ###
