"""initial

Revision ID: ba05e0c4b781
Revises: 
Create Date: 2025-11-27 17:24:07.670341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ba05e0c4b781'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('position', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('experience', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skills', mysql.JSON(), nullable=True),
    sa.Column('applied_date', mysql.DATETIME(), nullable=True),
    sa.Column('last_activity', mysql.DATETIME(), nullable=True),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('resume_url', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('recruiter', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('requisition_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('current_ctc', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('expected_ctc', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('notice_period', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('current_company', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=True),
    sa.Column('marital_status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('reject_reason', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], name='candidates_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('company', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('hashed_password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('company_size', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('company_desc', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requisition_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], name=op.f('notifications_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('file_url', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('uploaded_at', mysql.DATETIME(), nullable=True),
    sa.Column('candidate_id', mysql.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('files_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('requisitions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('position', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('department', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('experience', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=True),
    sa.Column('employment_type', mysql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN'), nullable=False),
    sa.Column('work_mode', mysql.ENUM('ONSITE', 'REMOTE', 'HYBRID'), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('priority', mysql.ENUM('HIGH', 'MEDIUM', 'LOW'), nullable=False),
    sa.Column('status', mysql.ENUM('OPEN', 'CLOSED', 'ON_HOLD', 'CANCELLED'), nullable=False),
    sa.Column('min_salary', mysql.FLOAT(), nullable=True),
    sa.Column('max_salary', mysql.FLOAT(), nullable=True),
    sa.Column('currency', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('positions_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skills', mysql.TEXT(), nullable=True),
    sa.Column('target_startdate', sa.DATE(), nullable=True),
    sa.Column('hiring_manager', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('job_description', mysql.TEXT(), nullable=True),
    sa.Column('recruiter_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('req_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('approval_status', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], name='fk_requisition_recruiter'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_requisitions_req_id'), 'requisitions', ['req_id'], unique=True)
    op.create_index(op.f('ix_requisitions_id'), 'requisitions', ['id'], unique=False)
    op.create_table('blobs',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('path', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('requisition_recruiter',
    sa.Column('requisition_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], name=op.f('requisition_recruiter_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('requisition_recruiter_ibfk_2')),
    sa.PrimaryKeyConstraint('requisition_id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('offers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('offer_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('app_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('grade', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('base', mysql.FLOAT(), nullable=False),
    sa.Column('allowances', mysql.JSON(), nullable=True),
    sa.Column('benefits', mysql.JSON(), nullable=True),
    sa.Column('variable_pay', mysql.FLOAT(), nullable=True),
    sa.Column('currency', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('status', mysql.ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'LETTER_GENERATED', 'ACCEPTED', 'DECLINED', 'EXPIRED'), nullable=True),
    sa.Column('expiry_date', mysql.DATETIME(), nullable=True),
    sa.Column('letter_blob_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['requisitions.id'], name='offers_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name='offers_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['letter_blob_id'], ['blobs.id'], name='offers_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_index(op.f('ix_offers_offer_id'), 'offers', ['offer_id'], unique=True)
    op.create_index(op.f('ix_offers_grade'), 'offers', ['grade'], unique=False)
    op.create_table('approval_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('offer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('approver_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state', mysql.ENUM('PENDING', 'APPROVED', 'REJECTED'), nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('acted_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('approval_records_ibfk_2')),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('approval_records_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_approval_records_state'), 'approval_records', ['state'], unique=False)
    op.create_index(op.f('ix_approval_records_offer_id'), 'approval_records', ['offer_id'], unique=False)
    op.create_table('candidate_activity_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('requisition_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('action', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('details', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('candidate_activity_logs_ibfk_4'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], name=op.f('candidate_activity_logs_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('candidate_activity_logs_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_candidate_activity_logs_id'), 'candidate_activity_logs', ['id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_price', mysql.FLOAT(), nullable=True),
    sa.Column('uom', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('taxable_value', mysql.FLOAT(), nullable=True),
    sa.Column('gst', mysql.FLOAT(), nullable=True),
    sa.Column('invoice_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('invoice_items_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_table('salary_bands',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('grade', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('min_amount', mysql.FLOAT(), nullable=False),
    sa.Column('max_amount', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_country_grade'), 'salary_bands', ['country', 'grade'], unique=True)
    op.create_index(op.f('ix_salary_bands_grade'), 'salary_bands', ['grade'], unique=False)
    op.create_index(op.f('ix_salary_bands_country'), 'salary_bands', ['country'], unique=False)
    op.create_table('scorecards',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('interview_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('technical_score', mysql.FLOAT(), nullable=True),
    sa.Column('behavioral_score', mysql.FLOAT(), nullable=True),
    sa.Column('cultural_score', mysql.FLOAT(), nullable=True),
    sa.Column('overall_recommendation', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('technical_comments', mysql.TEXT(), nullable=True),
    sa.Column('behavioral_comments', mysql.TEXT(), nullable=True),
    sa.Column('cultural_comments', mysql.TEXT(), nullable=True),
    sa.Column('overall_comments', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('scorecards_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('scorecards_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_scorecards_id'), 'scorecards', ['id'], unique=False)
    op.create_table('requisition_activity_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('requisition_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('action', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('details', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], name=op.f('requisition_activity_logs_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('requisition_activity_logs_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_requisition_activity_logs_id'), 'requisition_activity_logs', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('place_of_supply', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('payment_terms', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('service_description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('item_description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('total_amount', mysql.FLOAT(), nullable=True),
    sa.Column('pdf_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('envelope_id', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('invoice_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('invoice_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('po_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('currency', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('gstin', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('candidate_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('requisition_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interview_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('mode', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('datetime', mysql.DATETIME(), nullable=False),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('meeting_link', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('interviewers', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('feedback', mysql.TEXT(), nullable=True),
    sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('interviews_ibfk_1')),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], name=op.f('interviews_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('to_email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('body', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('error_message', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    # ### end Alembic commands ###
