name: Deploy Python App & React Frontend to Azure Web App - acme-recruitment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - uses: actions/checkout@v4
      
      # 1. --- FRONTEND BUILD STEP (CRITICAL) ---
      # This step must run first to create the 'frontend/build' directory.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a modern LTS version for React/Vite
          
      - name: Install Frontend Dependencies
        # Use the relative path to the repo root for working-directory
        working-directory: frontend 
        run: npm install
        
      - name: Build React Frontend
        # Use the relative path to the repo root for working-directory
        working-directory: frontend
        run: npm run build
        
      # 2. --- BACKEND SETUP ---
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install Backend Dependencies
        # Use the relative path to the repo root for working-directory
        working-directory: backend
        run: pip install -r requirements.txt

      # 3. --- DEPLOYMENT STEP ---
      - name: 'Deploy Backend & Frontend to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'acme-recruitment'
          slot-name: 'Production'
          # Deploy the root directory ('.') to include both 
          # 'backend/' and 'frontend/build/'.
          package: . 
          # Ensure this secret name is correct and indented properly:
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B4485BBD185742AAA1E9262EBEE7D61B }}





