name: Build and deploy Python app to Azure Web App - acme-recruitment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy: # Renaming the job to 'deploy' as it will handle the entire process
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      # Step 1: Deploy the 'backend' folder directly
      # This tells the Azure deployment action to ONLY package and send the 'backend' folder.
      # When Azure receives the package, the contents of 'backend' will be at the root of the
      # deployed site, and Oryx will find requirements.txt correctly.
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'acme-recruitment'
          slot-name: 'Production'
          # Set the package to the 'backend' directory
          package: ./backend
